// Test generated by RoostGPT for test gs-consuming-rest using AI Model gpt

package com.example.consumingrest;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

@ExtendWith(SpringExtension.class)
@SpringBootTest
public class ConsumingRestApplication_main4fc2a874f2Test {

    @InjectMocks
    private ConsumingRestApplication consumingRestApplication;

    @Mock
    private SpringApplication springApplication;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testMain_success() {
        String[] args = new String[] {"arg1", "arg2"};
        ConsumingRestApplication.main(args);
        verify(springApplication, times(1)).run(ConsumingRestApplication.class, args);
    }

    @Test
    public void testMain_noArgs() {
        String[] args = new String[] {};
        ConsumingRestApplication.main(args);
        verify(springApplication, times(1)).run(ConsumingRestApplication.class, args);
    }
}
