// Test generated by RoostGPT for test gs-consuming-rest using AI Model gpt

package com.example.consumingrest;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Quote_Quote2f66811864Test {

    private Quote quote;
    private Value value;

    @BeforeEach
    public void setUp() {
        value = Mockito.mock(Value.class);
        quote = new Quote("success", value);
    }

    @Test
    public void testGetType() {
        String expectedType = "success";
        assertEquals(expectedType, quote.type());
    }

    @Test
    public void testGetValue() {
        when(value.getId()).thenReturn(1L);
        when(value.getQuote()).thenReturn("test quote");

        Value expectedValue = new Value(1L, "test quote");
        assertEquals(expectedValue, quote.value());
    }

    @Test
    public void testGetTypeFailure() {
        String expectedType = "failure";
        assertEquals(expectedType, quote.type());
    }

    @Test
    public void testGetValueFailure() {
        when(value.getId()).thenReturn(2L);
        when(value.getQuote()).thenReturn("test quote 2");

        Value expectedValue = new Value(2L, "test quote 2");
        assertEquals(expectedValue, quote.value());
    }
}
