// Test generated by RoostGPT for test gs-consuming-rest using AI Model gpt

package com.example.consumingrest;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
public class Value_Value00869644a6Test {

    private Value valueUnderTest;

    @BeforeEach
    public void setUp() {
        valueUnderTest = new Value(1L, "Test quote");
    }

    @Test
    public void testGetId() {
        Long expectedId = 1L;
        Long actualId = valueUnderTest.id();
        assertEquals(expectedId, actualId, "The ID returned by the method does not match the expected ID");
    }

    @Test
    public void testGetQuote() {
        String expectedQuote = "Test quote";
        String actualQuote = valueUnderTest.quote();
        assertEquals(expectedQuote, actualQuote, "The quote returned by the method does not match the expected quote");
    }
}
